name: Deploy and Restart Bot

on:
  push:
    branches:
      - main  # Adjust if your default branch is named differently

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy repository content to VM
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.GOOBO_SSH_KEY }}
        source: "./"
        target: "/home/${{ secrets.VM_USER }}/goobo-bot"

    # - name: Stop existing bot instance
      # uses: appleboy/ssh-action@v1.0.0
      # with:
        # host: ${{ secrets.VM_HOST }}
        # username: ${{ secrets.VM_USER }}
        # key: ${{ secrets.GOOBO_SSH_KEY }}
        # port: ${{ secrets.PORT || '22' }}
        # script: |
          # cd /home/***/goobo-bot
          # pgrep -f goobo_bot.py && { (pkill -f goobo_bot.py &); echo "Bot instance stopped."; } || echo "No bot instance found to stop."
          # sleep 2
          # exit 0

    - name: Deploy and start new bot instance
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.GOOBO_SSH_KEY }}
        port: ${{ secrets.PORT || '22' }}
        script: |
          cd /home/***/goobo-bot
          nohup python3 goobo_bot.py > bot.log 2>&1 &
