name: Test Workflow Trigger

on:
  push:
    paths:
      - '.github/workflows/deploy.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Print a message
      run: echo "Workflow triggered successfully!"
